# Generated by Django 4.2.4 on 2023-09-02 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hoyou", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="person", name="image",),
    ]
