# Generated by Django 4.2.4 on 2023-09-03 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hoyou", "0003_record"),
    ]

    operations = [
        migrations.RenameModel(old_name="Record", new_name="Records",),
    ]
