# Generated by Django 4.2.4 on 2023-09-03 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hoyou", "0004_rename_record_records"),
    ]

    operations = [
        migrations.RenameModel(old_name="Records", new_name="Record",),
    ]
