# Generated by Django 4.2.5 on 2023-09-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hoyou", "0005_rename_records_record"),
    ]

    operations = [
        migrations.RemoveField(model_name="person", name="name",),
        migrations.AddField(
            model_name="person",
            name="birthday",
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="email",
            field=models.EmailField(default="no-adress@email.com", max_length=100),
        ),
        migrations.AddField(
            model_name="person",
            name="family_name",
            field=models.CharField(default="NO_NAME", max_length=100),
        ),
        migrations.AddField(
            model_name="person",
            name="first_name",
            field=models.CharField(default="NO_NAME", max_length=100),
        ),
        migrations.AddField(
            model_name="person",
            name="registered_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
