# Generated by Django 4.2.5 on 2023-09-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hoyou", "0006_remove_person_name_person_birthday_person_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="image",
            field=models.ImageField(null=True, upload_to="media/"),
        ),
    ]
