# Generated by Django 4.2.5 on 2023-09-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hoyou", "0009_alter_person_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="shuttai",
            field=models.CharField(
                choices=[("shukkin", "出勤"), ("taikin", "退勤"), ("sonota", "その他")],
                default="sonota",
                max_length=10,
            ),
        ),
    ]
