# Generated by Django 4.2.5 on 2023-09-07 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hoyou", "0013_alter_manager_username"),
    ]

    operations = [
        migrations.DeleteModel(name="Manager",),
    ]
