# Generated by Django 4.2.5 on 2023-09-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hoyou", "0014_delete_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="shuttai",
            field=models.CharField(
                choices=[("出勤", "出勤"), ("退勤", "退勤"), ("その他", "その他")],
                default="その他",
                max_length=10,
            ),
        ),
    ]
