# Generated by Django 4.2.5 on 2023-09-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hoyou", "0015_alter_record_shuttai"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="shuttai",
            field=models.CharField(
                choices=[("shukkin", "出勤"), ("taikin", "退勤"), ("sonota", "その他")],
                default="sonota",
                max_length=10,
            ),
        ),
    ]
