# Generated by Django 4.2.5 on 2023-09-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hoyou", "0016_alter_record_shuttai"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="family_name",
            field=models.CharField(default="NO_NAME", max_length=100, unique=True),
        ),
    ]
