# Generated by Django 4.2.5 on 2023-09-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hoyou", "0017_alter_person_family_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record", name="date", field=models.DateTimeField(),
        ),
    ]
