# Generated by Django 4.2.5 on 2023-09-14 05:28

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("hoyou", "0020_alter_person_email_alter_person_family_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="vector",
            field=picklefield.fields.PickledObjectField(
                blank=True, editable=False, null=True
            ),
        ),
    ]
